before_script:
  - curl -s https://raw.github.com/seomoz/qless-core/master/scripts/install_and_run_redis_2_6 | sh
  # From: https://github.com/jonleighton/poltergeist/blob/v1.0.0/.travis.yml#L5-7
  - sudo ci/install_phantomjs
  - "export PATH=phantomjs/bin:$PATH"
  - phantomjs --version
script: bundle exec rake
rvm:
  - 1.9.2
  - 1.9.3

