before_script:
  # From: https://github.com/jonleighton/poltergeist/blob/v1.0.0/.travis.yml#L5-7
  - sudo bin/install_phantomjs
  - "export PATH=phantomjs/bin:$PATH"
  - phantomjs --version
  - git submodule init
  - git submodule update
services:
  - redis-server
script: bundle exec rake
rvm:
  - 1.9.2
  - 1.9.3

